// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PawełGryglewiczLab5PracDom.Models;

namespace PawełGryglewiczLab5PracDom.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211208181959_ini")]
    partial class ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PawełGryglewiczLab5PracDom.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RailwayConnectionId")
                        .HasColumnType("int");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RailwayConnectionId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("PawełGryglewiczLab5PracDom.Models.RailwayConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceOfDepartureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfArrival")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("TimeOfDeparture")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("PlaceOfDepartureId");

                    b.HasIndex("TrainId");

                    b.ToTable("RailwayConnections");
                });

            modelBuilder.Entity("PawełGryglewiczLab5PracDom.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasTicketOffice")
                        .HasColumnType("bit");

                    b.Property<int>("PlatformsNumber")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("YearOfFound")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("PawełGryglewiczLab5PracDom.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("NumberOfCars")
                        .HasColumnType("int");

                    b.Property<string>("PowerType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Weigth")
                        .HasColumnType("int");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("PawełGryglewiczLab5PracDom.Models.Passenger", b =>
                {
                    b.HasOne("PawełGryglewiczLab5PracDom.Models.RailwayConnection", "RailwayConnection")
                        .WithMany("Passerngers")
                        .HasForeignKey("RailwayConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RailwayConnection");
                });

            modelBuilder.Entity("PawełGryglewiczLab5PracDom.Models.RailwayConnection", b =>
                {
                    b.HasOne("PawełGryglewiczLab5PracDom.Models.Station", "Destination")
                        .WithMany("DestinationInConnection")
                        .HasForeignKey("DestinationId");

                    b.HasOne("PawełGryglewiczLab5PracDom.Models.Station", "PlaceOfDeparture")
                        .WithMany("DeparturePlaceInConnection")
                        .HasForeignKey("PlaceOfDepartureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawełGryglewiczLab5PracDom.Models.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("PlaceOfDeparture");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("PawełGryglewiczLab5PracDom.Models.RailwayConnection", b =>
                {
                    b.Navigation("Passerngers");
                });

            modelBuilder.Entity("PawełGryglewiczLab5PracDom.Models.Station", b =>
                {
                    b.Navigation("DeparturePlaceInConnection");

                    b.Navigation("DestinationInConnection");
                });
#pragma warning restore 612, 618
        }
    }
}
